[app]

title = Quotex Bot
package.name = quotexbot
package.domain = com.quotexbot
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy,kivy-garden.webview,requests,numpy
orientation = landscape
fullscreen = 0
android.permissions = INTERNET, ACCESS_NETWORK_STATE, WRITE_EXTERNAL_STORAGE
android.api = 30
android.minapi = 21
android.sdk = 30
android.ndk = 23b
android.ndk_api = 21
android.enable_androidx = True
android.entrypoint = org.kivy.android.PythonActivity
android.apptheme = "@android:style/Theme.NoTitleBar"
android.copy_python_source = True
android.use_gradle = True
android.gradle_plugin_version = 3.4.0
android.use_androidx = True
android.launcher_name = Quotex Bot
android.activity_name = main
android.ndk = True
android.old_p4a = False
android.wakelock = True
android.debug = False
android.logcat = True
